uktrade/directory-sso

config/settings.py
config/urls.py
requirements.txt
sso/healthcheck/tests/test_views.py
sso/healthcheck/views.py
sso/user/serializers.py
sso/user/tests/test_views_oauth2.py
sso/user/views_oauth2.py

https://uktrade.atlassian.net/browse/ED-277

Add oauth2 authorised user profile api view

---

sso/templates/account/email/email_confirmation_message.html

[this task](https://uktrade.atlassian.net/browse/ED-297)
desktop:
mobile:

Add pretty email confirmation

---

README.md
config/settings.py
config/urls.py
docker/.env.test
docker/env-postgres.json
docker/env.json
docker/env.test.json
makefile
sso/user/tests/test_views.py
sso/user/views.py

[this task](https://uktrade.atlassian.net/browse/ED-195)

Add redirection to exportingisgreat on logout

---

makefile

sibling to [this pr](https://github.com/uktrade/directory-ui/pull/112/files)

Make cookies shared on dev environment

---

sso/templates/base.html
static/main.css

Make sso style similar to ui

---

config/settings.py
sso/user/tests/test_forms.py
sso/user/tests/test_views.py

[this task](https://uktrade.atlassian.net/browse/ED-363)

Add min length password validation

---

config/settings.py
config/urls.py
docker/env.json
docker/env.test.json
makefile
sso/templates/account/password_reset.html
sso/templates/account/password_reset_done.html
sso/templates/account/verification_sent.html
sso/templates/base.html
sso/templates/base_email_cta.html
sso/user/tests/test_urls.py
sso/user/views.py

[this task](https://uktrade.atlassian.net/browse/ED-240)

Add zendesk links

---

sso/templates/400.html
sso/templates/403.html
sso/templates/404.html
sso/templates/500.html

Add custom error templats

---

sso/user/forms.py

https://uktrade.atlassian.net/browse/ED-383

Capitalize Exporting

---

sso/templates/base.html

[this task](https://uktrade.atlassian.net/browse/ED-401)
- changed URL for contact us

URL changed for contact us

---

sso/templates/account/login.html
sso/templates/account/logout.html
sso/templates/account/password_change.html
sso/templates/account/password_reset.html
sso/templates/account/signup.html
sso/tests/test_template.py

https://uktrade.atlassian.net/browse/ED-400

Keep next param in url when form invalid

---

sso/templates/base.html

[this task](https://uktrade.atlassian.net/browse/ED-379)

Remove cookie message

---

sso/templates/base.html

[this task](https://uktrade.atlassian.net/browse/ED-392)

Update links on header and footer

---

sso/templates/account/login.html
sso/templates/account/logout.html
sso/templates/account/password_change.html
sso/templates/account/password_reset.html
sso/templates/account/signup.html
sso/tests/test_template.py

Reverts uktrade/directory-sso#49

Revert "Revert "Keep next param in url when form invalid""

---

package.json
sso/templates/base.html
static/javascripts/index.js
static/main.css
tests/javascripts/test_index.js

[this task](https://uktrade.atlassian.net/browse/ED-384)

Add menu toggle functionality

---

sso/templates/base_email_cta.html

[this task](https://uktrade.atlassian.net/browse/ED-394)

Update email to be branded

---

sso/templates/base.html
static/main.css

[this task](ED-384)
[this pr](https://github.com/uktrade/directory-sso/pull/48) introduced style problems.

Fix styles

---

sso/templates/account/signup.html

[this task] (https://uktrade.atlassian.net/browse/ED-413)
- copy added
- Link aded

copy and link added

---

sso/templates/account/signup.html

[this task] (https://uktrade.atlassian.net/browse/ED-413)
- changed URLS
- broke links up individually

URLs changed

---

README.md
config/settings.py
config/urls.py
docker/env.json
sso/user/views.py

This is just to clean up a tiny bit after #60

Redirect sso root - clean up after hurried PR

---

sso/templates/base.html
sso/templates/google_tag_manager_body.html
sso/templates/google_tag_manager_head.html
sso/tests/test_template.py

[this task](https://uktrade.atlassian.net/browse/ED-412)

Add google analytics

---

sso/templates/account/password_reset_done.html
sso/user/forms.py
sso/user/tests/test_forms.py
sso/user/tests/test_views.py

https://uktrade.atlassian.net/browse/ED-419

Protect password reset against email enumeration

---

docker/cmd-integration-test-webserver.sh
sso/user/management/commands/create_test_users.py

[this task](https://uktrade.atlassian.net/browse/ED-255)

Add integration test users

---

sso/templates/account/login.html
sso/templates/account/signup.html
sso/templates/base.html

[this task](https://uktrade.atlassian.net/browse/ED-326)

Make url labels consistent

---

sso/templates/account/email/password_reset_key_message.html
sso/templates/base_email_cta.html

[this task](https://uktrade.atlassian.net/browse/ED-422)

Update content of password reset email

---

sso/templates/base.html

`sso_is_logged_in` is a `directory-ui` thing. It does not exist in `directory-sso`.

Fix login state of header

---

requirements.txt
sso/templates/base.html

[this task](https://uktrade.atlassian.net/browse/ED-442)
[relies on this pr](https://github.com/uktrade/directory-constants/pull/3)

Add exporting is great service url

---

config/urls.py
sso/templates/400.html
sso/templates/403.html
sso/templates/404.html
sso/templates/500.html
sso/templates/account/password_reset.html
sso/templates/account/password_reset_done.html
sso/templates/account/verification_sent.html
sso/templates/base.html
sso/templates/base_email_cta.html

[this task](https://uktrade.atlassian.net/browse/ED-446)

Change namespacing of directory_constants urls to `constants`

---

sso/templates/base_email_cta.html
sso/templatetags/sso_email.py
sso/tests/test_template_tags.py

[this task](https://uktrade.atlassian.net/browse/ED-436)

Fix external links in emails

---

config/settings.py
sso/templates/account/login.html
sso/templates/account/signup.html
sso/templates/base.html
sso/user/context_processors.py
sso/user/tests/test_context_processors.py
sso/user/utils.py
sso/user/views.py

[this task](https://uktrade.atlassian.net/browse/ED-445)

Fix account logout link

---

sso/templates/base.html
static/main.css

[this task](https://uktrade.atlassian.net/browse/ED-431)

Improve style of non-field errors

---

static/main.css

[fix this](https://uktrade.atlassian.net/browse/ED-560)

Prevent invalid input styling

---

sso/templates/account/email/email_confirmation_message.html
sso/templates/account/email/password_reset_key_message.html
sso/templates/base_email_cta.html
sso/tests/test_template.py

Replace email button hyperlink with plaintext hyperlink

---

sso/templates/base_email_cta.html

[this task](https://uktrade.atlassian.net/browse/ED-596)

Ensure email HTML valid

---

config/urls.py
sso/user/tests/test_views.py
sso/user/views.py

[this task](https://uktrade.atlassian.net/browse/ED-609)

Show confirmation message on password reset

---

sso/user/forms.py
sso/user/tests/test_forms.py

[this task](https://uktrade.atlassian.net/browse/ED-675)

Prevent autofill of sensetive fields

---

sso/tests/test_adapters.py
sso/user/utils.py

https://uktrade.atlassian.net/browse/ED-661

Fix for next param validation

---

sso/tests/test_fixtures.py
test_fixtures/load_tests.json

https://uktrade.atlassian.net/browse/ED-723

Change load test fixture ids

---

config/settings.py
docker/env.json
docker/env.test.json
makefile
sso/context_processors.py
sso/templates/base.html
sso/tests/test_context_processors.py
sso/tests/test_template.py
static/javascripts/index.js

[this task](https://uktrade.atlassian.net/browse/ED-969)
will follow up with preventing update if the cookie is already present.

Add the utm params cookie storage

---

.gitignore
sso/templates/base.html
static/javascripts/index.js

Added UTM storage code (replication of FAB and FAS).

Ed 983 utm cookie storage

---

config/settings.py
requirements.txt
sso/api/filters.py
sso/api/tests/test_views_user.py
sso/api/views_user.py

[this task](https://uktrade.atlassian.net/browse/ED-1027)

Handle invalid dates on last login endpoint

---

sso/user/tests/test_views.py
sso/user/views.py

https://uktrade.atlassian.net/browse/ED-1182

Add sso_display_logged_in cookie

---

sso/templates/account/signup.html
static/main.css

[this task](https://uktrade.atlassian.net/browse/ED-1146)

Update copy of signup showing advantages

---

sso/templates/header.html

Fix header icons

---

sso/templates/account/login.html

ED-1209 Change wording on login form

---

sso/user/forms.py
sso/user/tests/test_forms.py

[this task](https://uktrade.atlassian.net/browse/ED-1243)

Add minmum password length help text

---

static/javascripts/index.js

ED-1262 Fix loop on null when regex fails to return result

---

sso/templates/account/email_confirm.html
sso/templates/account/login.html
sso/user/tests/test_views.py
sso/user/views.py

[this task](https://uktrade.atlassian.net/browse/ED-1376)

Redirect user back to `next` on email confirm

---

sso/templates/base_email_cta.html

[this task](https://uktrade.atlassian.net/browse/ED-1485)
[this task](https://uktrade.atlassian.net/browse/ED-1484)

Update the office address

---

sso/user/tests/test_widgets.py
sso/user/widgets.py

[this task](https://uktrade.atlassian.net/browse/ED-1660)

Add missing ID element to custom checkbox

---

sso/user/forms.py

In terms and conditions line, change "Exporting is Great" to "great.gov.uk"

ED-1682 Update content

---

sso/templates/account/email_confirm.html
sso/user/forms.py

[this task](https://uktrade.atlassian.net/browse/ED-1702)

Change e-mail to email

---

sso/user/admin.py
sso/user/tests/test_admin.py

[this task](https://uktrade.atlassian.net/browse/ED-1754)

Remove duplicate users from csv download

---

.coveragerc
config/settings.py
core/apps.py
core/management/commands/distributed_migrate.py
core/tests/test_management_commands.py
makefile
requirements.ini
requirements.txt

[this task](https://uktrade.atlassian.net/browse/ED-1772)

Add distributed migrate

---

sso/api/tests/test_views_user.py
sso/api/views_user.py

[this task](https://uktrade.atlassian.net/browse/ED-1950)

404 for sessions that have expired

---

sso/api/views_user.py

[part of this task](https://uktrade.atlassian.net/browse/ED-2188)

Fix password check endpoint

---

sso/healthcheck/tests/test_views.py
sso/healthcheck/views.py

This reverts commit 666ed96b27baa2ecdd39b6c85b0776a4270675aa.

Revert "Add signature check to api health check"

---

sso/templates/base.html

https://uktrade.atlassian.net/browse/ED-2604

Remove old jQuery, use new

---

sso/templates/account/login.html
sso/user/forms.py

https://uktrade.atlassian.net/browse/ED-2621

ED-2621 Changed 'login' to 'sign in'. Cleaned up formatting

---

requirements.in
requirements.txt
requirements_test.txt

[this task](https://uktrade.atlassian.net/browse/ED-2731)
[this task](https://uktrade.atlassian.net/browse/ED-2730)

Upgrade header and footer

---

sso/templates/account/signup.html
sso/user/forms.py
static/main.css

[this task](https://uktrade.atlassian.net/browse/ED-2776)

Improve style of forms

---

sso/user/tests/test_views.py
sso/user/views.py

https://uktrade.atlassian.net/browse/ED-2795

ED-2795 Updated contact us url to use correct env var

---

requirements.in
requirements.txt
requirements_test.txt

https://uktrade.atlassian.net/browse/ED-2867

ED-2867 Upgrade header/footer

---

config/settings.py
requirements.in
requirements.txt
requirements_test.txt

[part of this task](https://uktrade.atlassian.net/browse/ED-2933)

Fix healthcheck auth

---

requirements.in
requirements.txt
requirements_test.txt

Updated with the new automated script! 🎉 
https://uktrade.atlassian.net/browse/ED-3005

ED-3005 Updated header/footer with custom page link

---

requirements.in
requirements.txt
requirements_test.txt

https://uktrade.atlassian.net/browse/ED-3184

ED-3184 Updated header/footer with new events content

---

requirements.in
requirements.txt
requirements_test.txt
sso/templates/account/password_change.html
sso/templates/account/password_reset.html

[this task](https://uktrade.atlassian.net/browse/ED-3275)
[this task](https://uktrade.atlassian.net/browse/ED-3273)

Fix GA and password reset style

---

sso/templates/account/password_reset_from_key.html

[this task](https://uktrade.atlassian.net/browse/ED-3313)

Fix password reset button style

---

sso/testapi/tests/test_views.py
sso/testapi/views.py

This [ticket](https://uktrade.atlassian.net/browse/ED-3072)

ED-3072 testapi - delete user data

---

sso/testapi/tests/test_views.py
sso/testapi/views.py

This [ticket](https://uktrade.atlassian.net/browse/ED-3076)

ED-3076 - testapi - flag user email as verified or not

---

sso/templates/account/signup.html

https://uktrade.atlassian.net/browse/TT-98

content change to first 3 bullets

---

sso/templates/account/signup.html

Change to this page https://sso.trade.great.gov.uk/accounts/signup/

Add sign-in link to register page

---

sso/templates/account/signup.html

https://uktrade.atlassian.net/browse/TT-98

TT-98-change-trade-to-business

---

requirements.in
requirements.txt
requirements_test.txt

https://uktrade.atlassian.net/browse/TT-99

TT-99-trade-to-business-profile

---

requirements.in
requirements.txt
requirements_test.txt
sso/user/forms.py
sso/user/tests/test_forms.py

[this task](https://uktrade.atlassian.net/browse/TT-174)

Fix accessibility problem with check box

---

requirements.in
requirements.txt
requirements_test.txt
sso/templates/base.html

https://uktrade.atlassian.net/browse/CMS-148

Add cookie notice

---

.circleci/config.yml
Dockerfile
conf/settings.py
conf/urls.py
requirements.in
requirements.txt
requirements_test.txt
runtime.txt
sso/healthcheck/tests/test_views.py
sso/healthcheck/views.py

[this task](https://uktrade.atlassian.net/browse/TT-534)

Add sentry healthcheck

---

requirements.in
requirements.txt
requirements_test.txt

[this task](https://uktrade.atlassian.net/browse/TT-710)

Fix bad password reset token

---

conf/urls.py
requirements.in
requirements.txt
requirements_test.txt

[this task](https://uktrade.atlassian.net/browse/TT-918)

Upgrade requests for security vulnerability fix

---

sso/user/serializers.py
sso/user/tests/test_views_api.py
sso/user/views_api.py

[this task](https://uktrade.atlassian.net/browse/TT-1028)

Authenticate the user on creation

---

sso/templates/account/signup.html

[this task](https://uktrade.atlassian.net/browse/TT-979)

Remove obsolete content

---

sso/templates/account/login.html

Content updates

---

sso/verification/tests/test_view.py
sso/verification/views.py

[this task](https://uktrade.atlassian.net/browse/TT-1205)

Inform allauth of email verifiation on code verification

---

CHANGELOG.md
sso/user/admin.py
sso/user/tests/factories.py
sso/user/tests/test_views_api.py
sso/user/views_api.py

[this task](https://uktrade.atlassian.net/browse/TT-1353)

Prevent error caused by duplicate submission of user profile create

---

sso/templates/account/signup.html

Changed header to: Create an account
Changed body copy
Removed bullet list
Changed CTA

reg journey content update: Sign up

---

CHANGELOG.md
sso/templates/account/password_change.html

Fix breadcrumbs on change password page

---

CHANGELOG.md
conf/urls.py
sso/user/tests/test_views_api.py
sso/user/views_api.py

Tt 1760 personal details update

---

.circleci/config.yml
CHANGELOG.md
README.md
makefile
requirements.in
requirements.txt
requirements_test.txt
sso/templates/account/login.html
sso/templates/account/password_reset.html
sso/user/context_processors.py
sso/user/forms.py
sso/user/tests/test_forms.py
sso/user/tests/test_views.py
sso/user/views.py

Update directory components to add "no-validate" no cache middleware

---

CHANGELOG.md
sso/user/tests/test_views.py
sso/user/views.py

Send unverified users to verification page on login

---

CHANGELOG.md
sso/user/tests/test_views.py
sso/user/views.py

Tt 1953 remove login redirect for individual user

---

CHANGELOG.md
sso/templates/account/login.html

TT-1927 fix duplicate errors

---

CHANGELOG.md
conf/env/dev
conf/urls.py
sso/testapi/conftest.py
sso/testapi/tests/test_views.py
sso/testapi/views.py

TT-2197 add testapi endpoint to delete test users

---

sso/testapi/views.py

remove authentication_class for testapi endpoint

---

CHANGELOG.md
conf/settings.py
requirements.in
requirements.txt
requirements_test.txt

upgrade django and sentry client

---

CHANGELOG.md
sso/adapters.py
sso/user/tests/test_forms.py
sso/user/tests/test_views.py

redirect to resend verification code if not provided code

---

CHANGELOG.md
conf/settings.py
sso/user/context_processors.py
sso/user/tests/test_context_processors.py
sso/user/tests/test_views.py
sso/user/views.py

Cleaned up obsolete settings

---

CHANGELOG.md
conf/urls.py
sso/testapi/conftest.py
sso/testapi/tests/test_views.py
sso/testapi/views.py

TT-2285 create test users via testapi

---

CHANGELOG.md
sso/testapi/views.py

This is to avoid having test dependencies running in live/prod mode

replace test Factories with regular models

---

CHANGELOG.md
conf/settings.py
sso/user/serializers.py
sso/user/tests/test_utils.py
sso/user/utils.py

Expose social profile image

---

CHANGELOG.md
conf/settings.py
pytest.ini
sso/testapi/conftest.py
sso/testapi/tests/test_views.py
sso/testapi/views.py

AA-115 use correct test email domain

---

CHANGELOG.md
conf/settings.py
conf/urls.py
sso/user/tests/test_views.py
sso/user/views.py

TT-2332 - remove sign-up view

---

CHANGELOG.md
requirements_test.in
requirements_test.txt

Fix for codecov stuck

---

CHANGELOG.md
sso/user/models.py
sso/user/tests/test_views_api.py
sso/user/views_api.py

Added endpoint to delete lesson completed and refactor tests

---

CHANGELOG.md
sso/user/tests/test_views_api.py
sso/user/views_api.py

Fix bug on delete lesson completed api endpoint

---

CHANGELOG.md
sso/user/tests/test_views_api.py
sso/user/views_api.py

Staging release

---

CHANGELOG.md
requirements.in
requirements.txt
requirements_test.txt

GAA-27 - Bump directory-components version

---

CHANGELOG.md
sso/user/serializers.py
sso/user/views.py

GP2-763 Add social auth type to user profile

---

CHANGELOG.md

Added change log for Prod release 6.0.0

---

CHANGELOG.md

Added changelog for Prod release 6.

---

CHANGELOG.md
sso/user/tests/test_views.py
sso/user/views.py

[Bugfix] [GBAU-869] Flush session on logout from outside request

---

CHANGELOG.md
requirements.in
requirements.txt
requirements_test.txt

Upgraded cryptography package

---

requirements.in
requirements.txt
requirements_test.txt

Upgraded packages for security vulnerabilities

---

.circleci/config.yml
CHANGELOG.md
requirements.in
requirements.txt
requirements_test.txt

Upgraded directory-components package

---

CHANGELOG.md
requirements.in
requirements.txt
requirements_test.txt

Updated directory-components to fix contact link in the footer

---

CHANGELOG.md
sso/user/admin.py

Added Data retention fields for Admin UI

Added data retention fields for admin UI

---

.circleci/config.yml
CHANGELOG.md
runtime.txt

Bump up Python runtime

---

.circleci/config.yml
CHANGELOG.md
runtime.txt

upgrade-python-3-9-2

---

sso/adapters.py
sso/user/tests/test_views.py

GP2-2225-fix-prepopulation-email

---

CHANGELOG.md
sso/user/serializers.py

Expose social login attribute

---

CHANGELOG.md
sso/templates/400.html
sso/templates/403.html
sso/templates/500.html

GP2-2554-error-page-update-links 

---

sso/user/fixtures/questions.json

VFM questions fixture update

---

sso/user/fixtures/questions.json

UAT release

---

CHANGELOG.md
requirements.in
requirements.txt
requirements_test.txt

Bump directory-components

---

CHANGELOG.md
conf/settings.py

Add SSO_PROXY_LOGOUT_URL to settings

---

CHANGELOG.md
conf/settings.py

This reverts commit a6176626ee43c0ce95ce88fb89fe5bbbf056a33d.

Revert "Add SSO_PROXY_LOGOUT_URL to settings"

---

CHANGELOG.md

 update-cl-27-05-2021 

---

sso/management/commands/adhoc_notify_users.py
sso/tests/management/commands/conftest.py
sso/tests/management/commands/test_adhoc_notify_users.py

Adhoc script for notification for three year and old users

---

CHANGELOG.md
manifest.yml
requirements.in
requirements.txt
requirements_test.txt
runtime.txt

Pinned CF buildpack and upgraded python to 3.9.5

---

CHANGELOG.md
Dockerfile
conf/env/dev-docker
start.sh

 GP2-2867-dockerise-sso 

---

CHANGELOG.md
sso/tests/management/commands/conftest.py
sso/tests/management/commands/test_adhoc_notify_users.py

Fix test for adhoc notification

---

conf/env/dev-docker

GP2-3071 Use updated DB name to allow tests to run against docker DB

---

CHANGELOG.md
sso/user/admin.py

GP2-2445 JSON widget for VFM answer admin

---

conf/settings.py

 add-vfm-to-whitelist 

---

CHANGELOG.md
sso/api/tests/test_views_activity_stream.py
sso/api/views_activity_stream.py
sso/user/serializers.py
test_fixtures/user_vfm_tests.json

GP2-3074-pipeline-vfm-questions

---

CHANGELOG.md
sso/user/tests/test_views_api.py

Added test for partial user profile update

---

CHANGELOG.md
sso/user/tests/test_views_api.py
sso/user/views_api.py

GP2-3119 User basket

---

sso/verification/tests/test_view.py
sso/verification/views.py

This PR makes a successful code verification response include an `email` address needed for notifications on the client's side.
To do:

Return email address on successful code verification

---

CHANGELOG.md
sso/api/tests/test_views_activity_stream.py
sso/api/views_activity_stream.py
sso/user/serializers.py

 GP2-3180-VFM-add-user-hashID 

---

sso/templates/account/password_reset.html

Added meta description for password reset page

---

sso/api/tests/test_views_activity_stream.py
sso/api/views_activity_stream.py
sso/user/serializers.py

GP2-3904-add-mobile-activity-stream

---

requirements.in
requirements.txt
requirements_test.txt

Updated celery

---

CHANGELOG.md
sso/management/commands/notify_users.py
sso/tests/management/commands/test_notify_users.py

Bug fix regarding notification for data retention

---

CHANGELOG.md
sso/management/commands/manual_notify_users.py
sso/tests/management/commands/conftest.py
sso/tests/management/commands/test_manual_notify_users.py
sso/tests/management/commands/test_notify_users.py

Management command for sending data retention notifications

---

requirements.in
requirements.txt
requirements_test.txt

Pyjwt upgrade

---

CHANGELOG.md

Update changelog following release 9.5.0, and add missing entry for 9.4.2.

Post-release changelog update - 9.5.0

---

CHANGELOG.md

Update the changelog following the release of version 9.6.0.

Post-release changelog update 9.6.0

---

CHANGELOG.md
requirements.in
requirements.txt
requirements_test.txt

Django upgrade

---

conf/tests/test_wsgi.py
sso/templates/account/email_confirm.html
sso/templates/account/login.html
sso/templates/account/logout.html
sso/templates/account/password_change.html
sso/templates/account/password_reset.html
sso/templates/account/password_reset_done.html
sso/templates/account/password_reset_from_key.html
sso/templates/account/signup.html
sso/templates/account/verification_sent.html

Fix wrong path of base.html

---

requirements.in
requirements.txt
requirements_test.txt

Upgrade to whitenoise

---

requirements.in
requirements.txt
requirements_test.txt

Latest release sigauth broken the login process on great. degraded sigauth version fixing it.

Sigauth package degrade

---

requirements.in
requirements.txt
requirements_test.txt
sso/user/tests/test_admin.py

Dependencies upgrade

---

CHANGELOG.md
requirements.txt
requirements_test.txt

KLS-334 patch future 0.18.3

---

requirements.in
requirements.txt
requirements_test.txt
sso/tests/management/commands/conftest.py

KLS-507: Bump requests from 2.25.1 to 2.28.2

---

.circleci/config.yml
makefile
requirements_test.in
requirements_test.txt

Update codecov requirement

---

.gitignore
requirements.in
requirements.txt
requirements_test.txt

Upgrade sqlparse to 0.4.4 (venerability patch)

---

requirements.in
requirements.txt
requirements_test.txt

Upgrade Django to 3.2.19

---

1
requirements.txt
requirements_test.txt

This PR upgrades directory-sso to use sigauth 5.2.1

bump sigauth to 5.2.1

---

.circleci/config.yml
conf/urls.py
requirements.txt
requirements_test.txt
sso/management/commands/archive_users.py
sso/tests/management/commands/conftest.py
sso/tests/management/commands/test_notify_users.py
sso/tests/test_adapters.py
sso/user/models.py

this PR is to upgrade requests to use 2.31.0

upgrade requests

---

requirements.in
requirements.txt
requirements_test.txt

This PR is to bump whitenoise to 6.5.0 due to the recent django upgrade

upgraded whitenoise

---

conf/settings.py

This is to fix a bug when upgrading whitenoise

changed whitenoise staticfile_storage setting

---

requirements.in
requirements.txt
requirements_test.txt

Upgrade/kls 1005 bump cryptography 41.0,3

---

requirements.in
requirements.txt
requirements_test.in
requirements_test.txt

Upgrade cryptography, urllib3, pillow and GitPython to resolve security alerts

Upgrade cryptography, urllib3, pillow and GitPython

---

requirements.in
requirements.txt
requirements_test.in
requirements_test.txt

PR to merge to master for production release

Merge for release

---

manifest.yml

ALTERED Manifest file for Ubuntu upgrade.

ALTERED Manifest file for Ubuntu upgrade.

---

manifest.yml

UAT / PROD Release

---

requirements.in
requirements.txt
requirements_test.txt

Bump django to 4.1.13 and some other deps

Bump django to 4.1.13 and some other deps

---

.circleci/config.yml
.gitignore
requirements.in
requirements.txt
requirements_test.txt

KLS-1716 Upgrade django directory-sso

---

requirements.in
requirements.txt
requirements_test.in
requirements_test.txt

Bumped Django to 4.2.7

---

requirements.in
requirements.txt
requirements_test.txt

Bump pillow to 10.3.0

---

.circleci/config.yml

Bumped postgres in CircleCi to 16.2

Bumped postgres in CircleCi to 16.2

---

conf/settings.py
requirements.in
requirements.txt
requirements_test.txt

Added ASIM logging for DBT platform

Added ASIM logging

---

conf/settings.py
conf/urls.py
core/pingdom/services.py
core/tests/test_views.py
core/views.py
requirements.in
requirements.txt
requirements_test.txt

Add pingdom healthcheck for DBT Platform

Add pingdom healthcheck for DBT Platform - minor change

---

static/javascripts/index.js

Update the regular expression to include global flags.

Add global flag to regex

---

requirements.in
requirements.txt
requirements_test.txt

Bump requests

---

requirements.in
requirements.txt
requirements_test.txt

Upgrade to the cryptography package to fix vulnerability.

GREATUK-1182 bump cryptography package.

---

package.json

This change is required to allow new versions of node and npm build CSS artefact and OCI images. Specifically needed prior to DBT platform migration
- [x ] Upgraded any vulnerable dependencies.
- [x ] I have updated security dependencies

GREATUK-1237 upgrade dev dependencies for CSS development

---

requirements.in
requirements.txt
requirements_test.txt

Bumped django and sigauth

---

sso/management/commands/obsfucate_personal_details.py
sso/tasks.py
sso/tests/test_tasks.py

Management Command to be used in hotfix environment to mask sensitive Personal data

Feature greatuk 1731 obsfucate personal details

---

sso/management/commands/obsfucate_personal_details.py
sso/tests/test_tasks.py

Add guard against obsfucate in prod

Add guard against obsfucate in prod

---

conf/settings.py
sso/management/commands/obsfucate_personal_details.py

Feature greatuk 1731 add guard for obsfucate

Feature greatuk 1731 add guard for obsfucate

---

sso/management/commands/obsfucate_personal_details.py

Fix email count

---

sso/management/commands/archive_users.py

Update archive users to delete individual user 
We had a few requests to delete users from great as they signed up by mistake or no longer want their data to be present on great.
Reusing the archiving management command to delete users and their data based on their email .
Note: This process does not delete UKEA/ EYB data . Will be adding another management command in great-cms to deal with those data.

Update archive users to delete individual user 

---

sso/management/commands/obsfucate_personal_details.py

Release PR 

---

conf/env.py
conf/settings.py
sso/adapters.py
sso/user/tests/test_forms.py
sso/user/tests/test_views.py

Feature greatuk 1757 bgs emails

---

package-lock.json
package.json

Fix package dependency design system
