uktrade/directory-sso

config/urls.py
sso/templates/terms.html
sso/user/forms.py
sso/user/tests/test_forms.py
sso/user/tests/test_views.py
static/main.css

[this task](https://uktrade.atlassian.net/browse/ED-295)
I considered linking to UI's terms, but that would add extra complexity that is easily solved by duplicating the view here.

Add check for terms accepted

---

sso/user/forms.py
sso/user/tests/test_forms.py

currently the 'confirm email' field is after the 'agree' button.

Set field order of signup form

---

sso/constants.py
sso/templates/base_email_cta.html
sso/templatetags/sso_email.py
sso/tests/test_template_tags.py

`{% static` returns a relative url. That does not work for emails.

Serve email staticfiles from s3

---

sso/templates/base.html

Ad hoc request from Management (via Kai) so there's no ticket, some URLs have been changed in the header and the footer:
- Events (header and footer): https://events.trade.gov.uk
- Contact Us (Footer): https://contact-us.export.great.gov.uk/single_sign_on

URL changed

---

sso/templates/account/signup.html

On the global navigation "frequent exporters" is called "regular exporters", so make it the same on registration (aka user signup) page.

(fix) More consistent wording on registration page

---

sso/templates/account/email/password_reset_key_message.html
sso/templates/account/email/password_reset_key_message.txt
sso/user/tests/test_views.py

https://uktrade.atlassian.net/browse/ED-635
I was hoping to add somekind of bulletproof test for this not happening in the future, but since the problem was whether the next param comes through a POST or a GET and we have to specify what comes in GET and what comes in POST to django test client to run a test, this basically needs to be done in integration testing.

Fix missing next param in password reset url

---

config/settings.py

[this task](https://uktrade.atlassian.net/browse/ED-1550)
The header and footer context processor exposes the "contact us" value to the footer template.

Add missing context processor

---

config/urls.py
sso/api/tests/test_views_user.py
sso/api/views_user.py
sso/user/serializers.py

[this task](https://uktrade.atlassian.net/browse/ED-2049)
Check using the `session_key` rather than `email`, or `sso_id` to make it harder to brute force credentials.

Add password check endpoint

---

static/main.css

SSO's header looks slightly different to the other services because it's missing some common styling.

Improve header parity

---

config/urls.py
sso/healthcheck/tests/test_views.py
sso/healthcheck/views.py

[part of this task](https://uktrade.atlassian.net/browse/ED-2933)
This will be used by FAB to determine if FAB can communicate with API.
FAB is not using the healthcheck view because that has different permission requirements:
- healthcheck: permission determined via querystring value
- ping: permission determined via signature

Add ping view for healthcheck

---

conf/settings.py

default login url is not aware of `SCRIPT_NAME`, but `reverse_lazy` is.
https://docs.djangoproject.com/en/2.1/ref/settings/#login-url

Fix login url

---

manifest.yml

Lock down the buildpack version so not affected by GDS upgrades.

fix python buildpack version

---

CHANGELOG.md
conf/settings.py
requirements.in
requirements.txt
requirements_test.txt
sso/user/admin.py
sso/user/fixtures/questions.json
sso/user/models.py
sso/user/tests/test_models.py

This changeset enables management of `Question` objects from Django Admin.
To do:

Add questions to Django Admin

---

CHANGELOG.md
sso/user/fixtures/questions.json
sso/user/tests/test_utils.py
sso/user/tests/test_views_api.py
sso/user/utils.py

This changeset removes some of the VFM logic that automatically shuts down the questionnaire on completion - because access may be needed if the user uses the back button.
The logic has moved to the FE.
Also, a later set of questions fixture with input from Suraj

GP2-2353 VFM final page back button

---

makefile

Makefile secret script now uses sed directly to create the new file to avoid using -i option, which ensures compatibility with both Mac and Linux platforms (and prevents creating extra secrets-do-not-commit-e file on Mac).
The secrets file is only created if it does not exist, otherwise user is prompted to delete if they require a fresh one.
CONTEXT: This should make onboarding and fresh setup slightly easier and more consistent when using the Docker setup from https://github.com/uktrade/great-cms

GP2-3071 Improve make secrets script

---

CHANGELOG.md
Dockerfile
conf/urls.py
sso/api/tests/test_views_activity_stream.py
sso/api/views_activity_stream.py
sso/user/serializers.py
test_fixtures/user_vfm_tests.json

New AS activity to pull Value for Money  VFM survey into activity stream for consumption in data workspace.
We could have merged into the exiting SSOUser AS stream this would have made it simpler for maintenance but figured this is a separate usercase. Also VFM responses is probably more sensitive than USER data i.e less robust so these's value in keeping this uncoupled. So VFM responses won't break user feed.

GP2-3074-pipeline-vfm-survey 

---

CHANGELOG.md
conf/urls.py
sso/user/serializers.py
sso/user/tests/test_views_api.py
sso/verification/helpers.py
sso/verification/tests/test_view.py
sso/verification/views.py

This PR enables account verification via the query parameters `uidb64` (Base64 encoded user ID) and `token` to avoid PII captures in the form of email addresses.
To do:

[GP2-3344] Make account verification token based

---

CHANGELOG.md
sso/user/forms.py
sso/user/tests/test_forms.py

This PR adds validation on password reset.
To do:

[Bugfix] Validation on password reset

---

CHANGELOG.md
sso/user/forms.py
sso/user/tests/test_forms.py
sso/user/tests/test_utils.py
sso/user/tests/test_views_api.py
sso/user/utils.py
sso/user/views_api.py

API endpoint for creating a user returns a `409` (conflict) response when the email address is already registered.
To do:

Gp2 3406 notification already registered users

---

CHANGELOG.md
sso/user/tests/test_views_api.py
sso/user/views_api.py

Fix send notification when already registered email is found

---

CHANGELOG.md
sso/user/forms.py
sso/user/tests/test_forms.py
sso/user/tests/test_views_api.py
sso/user/views_api.py

Hotfix into master with the following fixes:
- Reset password validation
- Make user email case insensitive from user creation API endpoint

[HOTFIX INTO MASTER] Fixes for password validation and text case of email

---

.gitignore
CHANGELOG.md
sso/adapters.py
sso/constants.py
sso/user/tests/test_views.py
sso/user/views.py

This PR adds logic to the `LoginView` which will return a `401` response if the user logging in has not verified their account.
This will allow the client to more easily handle when an unverified user tries to login.
**NOTE**
Won't be merged until logic to handle a 401 response is released on great-cms.

Return 401 response when unverified user logs in

---

CHANGELOG.md
requirements.in

Bump Django from 3.2.15 to 3.2.16

---

requirements_test.in
requirements_test.txt

This PR upgrades git python from 3.1.31 to 3.1.32

KLS-1061 update git python

---

sso/templates/account/login.html
sso/templates/account/password_reset.html
sso/templates/base.html
sso/templatetags/canonical_url_tags.py
sso/tests/test_template_tags.py

Add canonical url to login pages including password reset page

Add canonical url to login pages

---

sso/api/tests/test_views_activity_stream.py
sso/api/views_activity_stream.py

To allow the new data-flow query the Activity Stream endpoints from outside of GOV.UK PaaS, this change removes the check on the X-Forwarded-For header that forbids any requests that contain such a header, which are the ones from the public internet.
The 3 endpoints are at the paths:
/api/v1/activity-stream/, powered by ActivityStreamViewSet
/api/v1/activity-stream/users/, powered by ActivityStreamDirectorySSOUsers
/api/v1/activity-stream/user-answers-vfm/, powered by ActivityStreamDirectorySSOUserAnswersVFM
To mitigate the increased risk by the exposure, an IP filter should be added in front of directory-sso (if it's not already running) should only allow the IP address of the new data-flow into these endpoints.

Expose Activity Stream endpoints to the public internet

---

conf/env.py
conf/settings.py
core/middleware.py
core/tests/test_middleware.py

As Directory SSO is not behind an IP filter it needs to check for the x-forwarded-for header in GovPaaS only. 
(Note: Although the HTTP header is called X-Forwarded-For, Django makes it available as request.META['HTTP_X_FORWARDED_FOR']. With the exception of content-length and content-type, any HTTP headers in the request are converted to request.META keys by converting all characters to uppercase, replacing any hyphens with underscores and adding an HTTP_ prefix to the name.)
The middleware I have introduced checks IP address that have been passed through via request.META['HTTP_X_FORWARDED_FOR'] against the ALLOWED_IPS settings.

Fix greatuk 1595 check x forward for header

---

core/middleware.py

Small PR to adjust the middleware that checks X-Forward-For headers in DBT PaaS. It now checks every IP address and only throws an error is an IP can not be found

Changed middleware to throw 200 if one IP is found

---

core/middleware.py
core/tests/test_middleware.py

This middleware is for gov paas only! I have not removed the copilot logic from the tests and added "if not is_copilot()"

Fix greatuk 1595 check x forward in gov paas

---

sso/api/views_activity_stream.py

Add some sentry logging to catch what is going on in PROD when activity stream urls fail.

Fix greatuk 1595 add sentry logging
